import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
const ImgixAPI = require("imgix-management-js");



export const getServerSideProps = () => {
   const imgix_api_key = '';
  
  const imgix = new ImgixAPI({
    apiKey: `${imgix_api_key}`
  });

  imgix.request(`assets/622f76522d67dbae5fb46268`)
  .then(response => console.log(JSON.stringify(response, null, 2)))
  

  return { props: {message: "helloWorld"}};
}



export default function Home({message}) {
  console.log(message)
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}


